import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signIn, signOut, useSession } from 'next-auth/react'
import { trpc } from '../utils/trpc'
import PopularMovies from '../components/UI/PopularMovies'

const Home: NextPage = () => {
    const hello = trpc.example.hello.useQuery({ text: 'from tRPC' })
    const movies = trpc.movie.getPopularMovies.useQuery()

    return (
        <>
            <Head>
                <title>Movielist</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute z-[-1] h-full w-full ">
                <div className="mt-24 ml-72 mr-24">
                    {!movies.data ? (
                        <div>Loading...</div>
                    ) : (
                        <PopularMovies movies={movies.data} />
                    )}
                </div>
            </div>
        </>
    )
}

export default Home

const AuthShowcase: React.FC = () => {
    const { data: sessionData } = useSession()

    const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
        undefined, // no input
        { enabled: sessionData?.user !== undefined }
    )

    return (
        <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white">
                {sessionData && (
                    <span>Logged in as {sessionData.user?.name}</span>
                )}
                {secretMessage && <span> - {secretMessage}</span>}
            </p>
            <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={sessionData ? () => signOut() : () => signIn()}
            >
                {sessionData ? 'Sign out' : 'Sign in'}
            </button>
        </div>
    )
}
