import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "@/utils/api";
import Sidebar from "@/components/Sidebar";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen place-items-center bg-white">
        <div className="navbar absolute top-0 left-0 bg-base-100">
          <div className="ml-12 flex-1">
            <a className="btn-ghost btn text-xl normal-case">daisyUI</a>
          </div>
          <div className="flex-none gap-2">
            <div className="dropdown-end dropdown">
              {sessionData ? (
                <label tabIndex={0} className="btn-ghost btn-circle avatar btn">
                  <div className="w-10 rounded-full">
                    <img src={sessionData.user.image!!} />
                  </div>
                </label>
              ) : null}
              <ul
                tabIndex={0}
                className="dropdown-content menu rounded-box menu-compact mt-3 w-52 bg-base-100 p-2 shadow"
              >
                <li>
                  <a className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </a>
                </li>
                <li>
                  <a>Settings</a>
                </li>
                <li>
                  <button onClick={() => void signOut()}>Logout</button>
                </li>
              </ul>
            </div>
          </div>
        </div>
        {!sessionData ? (
          <button className="btn-wide btn" onClick={() => void signIn()}>
            Sign in
          </button>
        ) : null}
        <Sidebar />
      </main>
    </>
  );
};

export default Home;
